# Generated by Django 3.2.11 on 2022-01-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
